//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoMarker.Frontiers.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoMarker.Frontiers.Core.Resources.CoreMessages", typeof(CoreMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has failed to start. CommandGuid: {0}.
        /// </summary>
        public static string CommandSerivce_Process_StartFailure {
            get {
                return ResourceManager.GetString("CommandSerivce.Process.StartFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} command has failed..
        /// </summary>
        public static string CommandService_Failure {
            get {
                return ResourceManager.GetString("CommandService.Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to be deleted was not found..
        /// </summary>
        public static string CommandService_FileNotFound {
            get {
                return ResourceManager.GetString("CommandService.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task result was found. CommandGuid: {0}.
        /// </summary>
        public static string CommandService_Process_NoTask {
            get {
                return ResourceManager.GetString("CommandService.Process.NoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} command was rejected. No process has been created. .
        /// </summary>
        public static string CommandService_Rejected {
            get {
                return ResourceManager.GetString("CommandService.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Error: {0}.
        /// </summary>
        public static string CommandService_StdErr {
            get {
                return ResourceManager.GetString("CommandService.StdErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Out: {0}.
        /// </summary>
        public static string CommandService_StdOut {
            get {
                return ResourceManager.GetString("CommandService.StdOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGuid: {0}, Command: {1}.
        /// </summary>
        public static string CommandService_TaskInfo {
            get {
                return ResourceManager.GetString("CommandService.TaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure has occurred attempting to execute the underlying command: {0}.
        /// </summary>
        public static string Controller_CommandFailure {
            get {
                return ResourceManager.GetString("Controller.CommandFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command was rejected in {0}..
        /// </summary>
        public static string Controller_CommandRejected {
            get {
                return ResourceManager.GetString("Controller.CommandRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred while processing {0}. .
        /// </summary>
        public static string Controller_Failure {
            get {
                return ResourceManager.GetString("Controller.Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} process completed successfully, but the result was null..
        /// </summary>
        public static string Controller_NullStream {
            get {
                return ResourceManager.GetString("Controller.NullStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cleanup job configuration error. {0}.
        /// </summary>
        public static string FileCleanupJob_ConfigurationError {
            get {
                return ResourceManager.GetString("FileCleanupJob.ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File output working directory does not exist. .
        /// </summary>
        public static string FileCleanupJob_NoWorkingDirectory {
            get {
                return ResourceManager.GetString("FileCleanupJob.NoWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total request directories found..
        /// </summary>
        public static string FileCleanupJob_RequestDirectoriesFound {
            get {
                return ResourceManager.GetString("FileCleanupJob.RequestDirectoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Request is older than {1} days. Removing..
        /// </summary>
        public static string FileCleanupJob_RequestOverCutoff {
            get {
                return ResourceManager.GetString("FileCleanupJob.RequestOverCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Request is younger than {1} days. .
        /// </summary>
        public static string FileCleanupJob_RequestUnderCutoff {
            get {
                return ResourceManager.GetString("FileCleanupJob.RequestUnderCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting file cleanup job. {0}.
        /// </summary>
        public static string FileCleanupJob_Starting {
            get {
                return ResourceManager.GetString("FileCleanupJob.Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;addresses&quot;: [{&quot;id&quot;: &quot;1&quot;, &quot;address&quot;: &quot;123 St&quot;}, {&quot;id&quot;: &quot;2&quot;, &quot;address&quot;: &quot;987 Road&quot;}]}.
        /// </summary>
        public static string JsonAddressFormat {
            get {
                return ResourceManager.GetString("JsonAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;addresses&quot;: [{&quot;id&quot;: &quot;1&quot;, &quot;address&quot;: &quot;123 St&quot;}, {&quot;id&quot;: &quot;2&quot;, &quot;address&quot;: &quot;987 Road&quot;}], &quot;services&quot;: [&quot;service1&quot;, &quot;service2], &quot;site&quot;:&quot;site&quot;, &quot;year&quot;:2020}.
        /// </summary>
        public static string JsonCompositeFormat {
            get {
                return ResourceManager.GetString("JsonCompositeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{&quot;records&quot;: [{{&quot;lat&quot;:&quot;0.00&quot;, &quot;lon&quot;:&quot;0.00&quot;}},{{&quot;lat&quot;:&quot;0.00&quot;, &quot;lon&quot;:&quot;0.00&quot;}}]{0}}}.
        /// </summary>
        public static string JsonLatLonFormat {
            get {
                return ResourceManager.GetString("JsonLatLonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh and contact support if this issue persists.
        /// </summary>
        public static string UiController_LoadFailureMessage {
            get {
                return ResourceManager.GetString("UiController.LoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not contain any blank rows..
        /// </summary>
        public static string ValidatorController_FileBlankRowsMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileBlankRowsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must NOT contain the headers &apos;lat&apos;, &apos;lon&apos;, &apos;score&apos;, or &apos;precision&apos;..
        /// </summary>
        public static string ValidatorController_FileCannotHaveGeocodedColumns {
            get {
                return ResourceManager.GetString("ValidatorController.FileCannotHaveGeocodedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not contain duplicate header columns..
        /// </summary>
        public static string ValidatorController_FileDuplicateHeadersMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileDuplicateHeadersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not be empty..
        /// </summary>
        public static string ValidatorController_FileEmptyMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not exceed {0} rows..
        /// </summary>
        public static string ValidatorController_FileExceedsRowCountMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileExceedsRowCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot be more than {0}.
        /// </summary>
        public static string ValidatorController_FileExceedsSize {
            get {
                return ResourceManager.GetString("ValidatorController.FileExceedsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has the incorrect content type. Expecting: {0}.
        /// </summary>
        public static string ValidatorController_FileIncorrectContentTypeMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileIncorrectContentTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must contain the headers &apos;lat&apos; and &apos;lon&apos;..
        /// </summary>
        public static string ValidatorController_FileIncorrectSchemaGeocodedMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileIncorrectSchemaGeocodedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must contain the headers &apos;ID&apos; (case insensitive) and &apos;address&apos; (case sensitive)..
        /// </summary>
        public static string ValidatorController_FileNeedsGeocodeColumns {
            get {
                return ResourceManager.GetString("ValidatorController.FileNeedsGeocodeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not be null..
        /// </summary>
        public static string ValidatorController_FileNullMessage {
            get {
                return ResourceManager.GetString("ValidatorController.FileNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lat must not be empty..
        /// </summary>
        public static string ValidatorController_GeocodedJsonLatEmptyMessage {
            get {
                return ResourceManager.GetString("ValidatorController.GeocodedJsonLatEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lon must not be empty..
        /// </summary>
        public static string ValidatorController_GeocodedJsonLonEmptyMessage {
            get {
                return ResourceManager.GetString("ValidatorController.GeocodedJsonLonEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one address must be present..
        /// </summary>
        public static string ValidatorController_JsonAddressEmptyMessage {
            get {
                return ResourceManager.GetString("ValidatorController.JsonAddressEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request cannot exceed {0} addresses..
        /// </summary>
        public static string ValidatorController_JsonExceedsAddressCountMessage {
            get {
                return ResourceManager.GetString("ValidatorController.JsonExceedsAddressCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON body is not in the correct format. Please use the format: {0}.
        /// </summary>
        public static string ValidatorController_JsonIncorrectFormatMessage {
            get {
                return ResourceManager.GetString("ValidatorController.JsonIncorrectFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the addresses were able to be geocoded, all subsequent services have been cancelled. Please double check the address format and try again.
        /// </summary>
        public static string ValidatorController_NoAddressesGeocoded {
            get {
                return ResourceManager.GetString("ValidatorController.NoAddressesGeocoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must NOT include &apos;{0}&apos; for the {1} service..
        /// </summary>
        public static string ValidatorController_ReservedFileName {
            get {
                return ResourceManager.GetString("ValidatorController.ReservedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site must not be empty..
        /// </summary>
        public static string ValidatorController_SiteEmptyMessage {
            get {
                return ResourceManager.GetString("ValidatorController.SiteEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site must be one of: {0}.
        /// </summary>
        public static string ValidatorController_SiteInvalidMessage {
            get {
                return ResourceManager.GetString("ValidatorController.SiteInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site must not be null..
        /// </summary>
        public static string ValidatorController_SiteNullMessage {
            get {
                return ResourceManager.GetString("ValidatorController.SiteNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize the JSON request.
        /// </summary>
        public static string ValidatorController_UnableToDeserializeMessage {
            get {
                return ResourceManager.GetString("ValidatorController.UnableToDeserializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not include spaces or special characters..
        /// </summary>
        public static string ValidatorController_ValidateFileName {
            get {
                return ResourceManager.GetString("ValidatorController.ValidateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year must be one of: {0}.
        /// </summary>
        public static string ValidatorController_YearInvalidMessage {
            get {
                return ResourceManager.GetString("ValidatorController.YearInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year must not be null..
        /// </summary>
        public static string ValidatorController_YearNullMessage {
            get {
                return ResourceManager.GetString("ValidatorController.YearNullMessage", resourceCulture);
            }
        }
    }
}
